from ex1.factories import HealingCreatureFactory, TransformCreatureFactory

if __name__ == "__main__":
    print("Testing Creature with healing capability")
    print("\tbase:")
    hf = HealingCreatureFactory()
    base = hf.create_base()
    evolved = hf.create_evolved()
    print(base.describe())
    print(base.attack())
    print(base.heal())
    print("\tevolved:")
    print(evolved.describe())
    print(evolved.attack())
    print(evolved.heal())

    print("Testing Creature with transform capability")
    print("\tbase:")
    tf = TransformCreatureFactory()
    base = tf.create_base()
    evolved = tf.create_evolved()
    print(base.describe())
    print(base.attack())
    print(base.transform())
    print(base.attack())
    print(base.revert())
    print("\tevolved:")
    print(evolved.describe())
    print(evolved.attack())
    print(evolved.transform())
    print(evolved.attack())
    print(evolved.revert())
